# default['easybake-workstation']['ingredients']['ubuntu']['desc']='Ubuntu ISO'
# default['easybake-workstation']['ingredients']['ubuntu']['version']='12.04.2'
default['easybake-workstation']['ingredients']['windows']['desc']='Windows ISO'
default['easybake-workstation']['ingredients']['virtualbox']['desc']='Virtualbox'
default['easybake-workstation']['ingredients']['vagrant']['desc']='Vagrant'
default['easybake-workstation']['ingredients']['sublimetext']['desc']='Sublime Text'
#default['easybake-workstation']['ingredients']['chef']['desc']='Sublime Text'
